ARM support
Signed-off-by: Artem Glazychev <artem.glazychev@xored.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -12,20 +12,65 @@ on:
     paths-ignore:
       - '**.md'
 jobs:
-  yamllint:
-    name: yamllint
+  setup_github_runner:
+    name: Setup actions runner
     runs-on: ubuntu-latest
+    env:
+      METAL_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
+      METAL_PROJECT_ID: ${{ secrets.PACKET_PROJECT_ID }}
+      RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
+      SERVER_TYPE: "c3.medium.x86"
+      METRO: da
     steps:
-      - name: Check out code into the Go module directory
+      - name: Check out code
         uses: actions/checkout@v2
-      - name: yaml-lint
-        uses: ibiqlik/action-yamllint@v1
-        with:
-          config_file: .ci/yamllint.yml
-          strict: true
+      - name: Install metal CLI
+        run: |
+          curl -L https://github.com/equinix/metal-cli/releases/download/v0.15.0/metal-linux-amd64 -o metal
+          chmod +x ./metal
+          mv ./metal /usr/local/bin/metal
+          metal -v
+      - name: Setup ssh
+        id: setup_ssh
+        run: |
+          echo $PACKET_SSH_KEY > /tmp/sshkey
+          chmod 600 /tmp/sshkey
+          echo "Step1"
+          eval `ssh-agent -s`
+          echo "Step2"
+          ssh-add /tmp/sshkey
+          echo "Step3"
+          ssh-keygen -f /tmp/sshkey -y > /tmp/sshkey.pub
+          echo "Step4"
+          metal ssh-key create --key "$(cat /tmp/sshkey.pub)" --label nsm-govpp-builder-ssh -o json | jq -r '.id'
+          echo "Step5"
+        env:
+          PACKET_SSH_KEY: ${{ secrets.PACKET_SSH_KEY }}
+      - name: Create server
+        run: |
+          metal device create -p $METAL_PROJECT_ID -P $SERVER_TYPE -m $METRO -H nsm-govpp-builder -O ubuntu_20_04
+          max_retry=10
+          counter=0
+          until [ "$state" == "active" ]
+          do
+            sleep 30
+            [[ counter -eq $max_retry ]] && echo "Failed!" && exit 1
+            state=$(metal device get -p $METAL_PROJECT_ID -o json | jq -r '.[] | select(.hostname=="nsm-govpp-builder") | .state')
+            echo "Try #$counter"
+            ((counter++))
+          done
+      - name: Setup actions runner
+        working-directory: ${{ github.repository }}
+        run: |
+          SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /tmp/sshkey"
+          server_ip=$(metal device get -p $METAL_PROJECT_ID -o json | jq -r '.[] | select(.hostname=="nsm-govpp-builder") | .ip_addresses[] | select(.public==true and .address_family==4) | .address')
+          scp ${SSH_OPTS} scripts/setup-actions-runner.sh root@${server_ip}:setup-actions-runner.sh
+          ssh ${SSH_OPTS} root@${server_ip} ./setup-actions-runner.sh $RUNNER_TOKEN
+
   build:
     name: build
-    runs-on: ubuntu-latest
+    needs: setup_github_runner
+    runs-on: self-hosted
     outputs:
       docker_tag: ${{ steps.docker_push.outputs.docker_tag }}
     steps:
@@ -34,116 +79,42 @@ jobs:
       - uses: actions/setup-go@v1
         with:
           go-version: 1.20.5
-      - name: Set Swap Space
-        uses: pierotofy/set-swap-space@v1.0
-        with:
-          swap-size-gb: 4
-      - name: Memory usage
-        run: free -m
-      - name: List installed packages
-        run: dpkg -la
-      - name: Free Disk Space for Docker
+      - name: Setup actions runner
         run: |
-          df -h
-          sudo apt-get remove aria2 azure-cli shellcheck rpm xorriso zsync \
-               clang-12 lld-12 clang-format-12 \
-               clang-13 lld-13 clang-format-13 \
-               clang-14 lld-14 clang-format-14 \
-               g++-9 g++-10 g++-12 g++-11 gfortran-9 gfortran-10 gfortran-11 google-chrome-stable \
-               google-cloud-sdk \
-               imagemagick \
-               libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional \
-               mercurial apt-transport-https mono-complete mysql-client libmysqlclient-dev \
-               mysql-server mssql-tools unixodbc-dev yarn libssl-dev \
-               libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
-               php-common \
-               php-pear \
-               php8.1 \
-               php8.1-amqp \
-               php8.1-apcu \
-               php8.1-bcmath \
-               php8.1-bz2 \
-               php8.1-cgi \
-               php8.1-cli \
-               php8.1-common \
-               php8.1-curl \
-               php8.1-dba \
-               php8.1-dev \
-               php8.1-enchant \
-               php8.1-fpm \
-               php8.1-gd \
-               php8.1-gmp \
-               php8.1-igbinary \
-               php8.1-imagick \
-               php8.1-imap \
-               php8.1-interbase \
-               php8.1-intl \
-               php8.1-ldap \
-               php8.1-mbstring \
-               php8.1-memcache \
-               php8.1-memcached \
-               php8.1-mongodb \
-               php8.1-msgpack \
-               php8.1-mysql \
-               php8.1-odbc \
-               php8.1-opcache \
-               php8.1-pcov \
-               php8.1-pgsql \
-               php8.1-phpdbg \
-               php8.1-pspell \
-               php8.1-readline \
-               php8.1-redis \
-               php8.1-snmp \
-               php8.1-soap \
-               php8.1-sqlite3 \
-               php8.1-sybase \
-               php8.1-tidy \
-               php8.1-xdebug \
-               php8.1-xml \
-               php8.1-xsl \
-               php8.1-yaml \
-               php8.1-zip \
-               php8.1-zmq \
-               snmp pollinate libpq-dev powershell ruby-full nginx shim-signed \
-               libnginx-mod-http-image-filter libmono-system-web4.0-cil monodoc-http \
-               sphinxsearch subversion -yq --allow-remove-essential
-          sudo apt-get autoremove -y
-          sudo apt-get autoclean -y
-          sudo rm -rf /usr/local/lib/android
-          sudo apt clean
-          docker rmi $(docker image ls -aq)
-          df -h
-      - name: Docker Build
+          sleep 180
+  delete_github_runner:
+    name: Delete actions runner
+    needs: build
+    runs-on: ubuntu-latest
+    env:
+      METAL_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
+      METAL_PROJECT_ID: ${{ secrets.PACKET_PROJECT_ID }}
+      RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
+    steps:
+      - name: Check out code
+        uses: actions/checkout@v2
+      - name: Install metal CLI
         run: |
-          docker build .
-          VPP_VERSION=$(docker run $(docker build -q . --target version))
-          echo "VPP_VERSION=${VPP_VERSION}" >> $GITHUB_ENV
-          TAG=v${VPP_VERSION/\~/-}
-          echo "TAG=${TAG}" >> $GITHUB_ENV
-          docker build -t ghcr.io/${{github.repository}}/vpp:${TAG} . --target vpp
-          docker build -t ghcr.io/${{github.repository}}/vpp-dbg:${TAG} . --target vpp-dbg
-      - name: Generate files
-        run: go generate ./...
-      - name: Check for changes in generated code
-        run: |
-          git diff -- binapi || (echo "Rerun go generate ./... locally and resubmit" && exit -1)
-      - name: Go Build
-        run: go build ./...
-      - name: Login to GitHub Container Registry
-        id: docker_login
-        if: ${{ github.event_name == 'push' }}
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Docker Push
-        id: docker_push
-        if: steps.docker_login.outcome == 'success'
-        run: |
-          docker push ghcr.io/${{github.repository}}/vpp:${TAG}
-          docker push ghcr.io/${{github.repository}}/vpp-dbg:${TAG}
-          echo docker_tag=${TAG} >> $GITHUB_OUTPUT
+          curl -L https://github.com/equinix/metal-cli/releases/download/v0.15.0/metal-linux-amd64 -o metal
+          chmod +x ./metal
+          mv ./metal /usr/local/bin/metal
+          metal -v
+      - name: Delete github runner
+        run:
+          echo $SSH_KEY > /tmp/sshkey         
+          SSH_OPTS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -i /tmp/sshkey"
+          server_ip=$(metal device get -p $METAL_PROJECT_ID -o json | jq -r '.[] | select(.hostname=="nsm-govpp-builder") | .ip_addresses[] | select(.public==true and .address_family==4) | .address')
+          scp ${SSH_OPTS} scripts/setup-actions-runner.sh root@${server_ip}:delete-actions-runner.sh
+          ssh ${SSH_OPTS} root@${server_ip} ./delete-actions-runner.sh $RUNNER_TOKEN
+          
+          device_id=$(metal device get -p $METAL_PROJECT_ID -o json | jq -r '.[] | select(.hostname=="nsm-govpp-builder") | .id')
+          metal device delete -f -i $device_id
+          
+          ssh_id=$(metal ssh-key get -o json | jq -r '.[] | select(.label=="nsm-govpp-builder-ssh") | .id')
+          metal ssh-key delete -f -i $ssh_id
+        env:
+          SSH_KEY: ${{ secrets.PACKET_SSH_KEY }}
+
   update_dependent_repositories:
     name: update_dependent_repositories
     needs: build
